BACKBONE2D:
  YOLOv8:
    ver : m

    PRETRAIN:
      n : weights/backbone2D/YOLOv8/v8_n.pth
      s : weights/backbone2D/YOLOv8/v8_s.pth
      m : weights/backbone2D/YOLOv8/v8_m.pth
      l : weights/backbone2D/YOLOv8/v8_l.pth
      x : weights/backbone2D/YOLOv8/v8_x.pth

BACKBONE3D:

  MOBILENET:
    width_mult: 2.0

    PRETRAIN:
      width_mult_0.5x  : weights/backbone3D/mobilenet/kinetics_mobilenet_0.5x_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/mobilenet/kinetics_mobilenet_1.0x_RGB_16_best.pth
      width_mult_1.5x  : weights/backbone3D/mobilenet/kinetics_mobilenet_1.5x_RGB_16_best.pth
      width_mult_2.0x  : weights/backbone3D/mobilenet/kinetics_mobilenet_2.0x_RGB_16_best.pth

  MOBILENETv2:
    width_mult: 1.0

    PRETRAIN:
      width_mult_0.2x  : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_0.2x_RGB_16_best.pth
      width_mult_0.45x : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_0.45x_RGB_16_best.pth
      width_mult_0.7x  : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_0.7x_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_1.0x_RGB_16_best.pth

  SHUFFLENET:
    width_mult: 2.0

    PRETRAIN:
      width_mult_0.5x  : weights/backbone3D/shufflenet/kinetics_shufflenet_0.5x_G3_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/shufflenet/kinetics_shufflenet_1.0x_G3_RGB_16_best.pth
      width_mult_1.5x  : weights/backbone3D/shufflenet/kinetics_shufflenet_1.5x_G3_RGB_16_best.pth
      width_mult_2.0x  : weights/backbone3D/shufflenet/kinetics_shufflenet_2.0x_G3_RGB_16_best.pth

  SHUFFLENETv2:
    width_mult: 2.0

    PRETRAIN:
      width_mult_0.25x : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_0.25x_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_1.0x_RGB_16_best.pth
      width_mult_1.5x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_1.5x_RGB_16_best.pth
      width_mult_2.0x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_2.0x_RGB_16_best.pth
      
  I3D:
    PRETRAIN:
      default: weights/backbone3D/I3D/rgb_imagenet.pth
  
  RESNET:
    ver : 101

    PRETRAIN:
      ver_18 : weights/backbone3D/resnet/kinetics_resnet_18_RGB_16_best.pth
      ver_50 : weights/backbone3D/resnet/kinetics_resnet_50_RGB_16_best.pth
      ver_101: weights/backbone3D/resnet/kinetics_resnet_101_RGB_16_best.pth

  RESNEXT:
    ver : 101

    PRETRAIN:
      ver_101 : weights/backbone3D/resnext/resnext-101-kinetics.pth

LOSS:
  TAL:
    top_k: 20  # Increased for HD
    alpha: 0.5
    beta: 6.0
    radius: 7.5  # Increased from 2.5 for HD
    soft_label: False
    scale_cls_loss: 1.5  # Adjusted for HD
    scale_box_loss: 22.5 # Adjusted for HD (7.5 * 3)
    scale_dfl_loss: 4.5  # Adjusted for HD

  SIMOTA:
    top_k: 20  # Increased for HD
    gamma: 0.5
    radius: 7.5  # Increased for HD
    mode: balance
    soft_label: True
    dynamic_k: True  # Enabled for HD
    dynamic_top_k: 120  # Increased for HD (40 * 3)
    scale_cls_loss: 1.5  # Adjusted for HD
    scale_box_loss: 22.5 # Adjusted for HD
    scale_dfl_loss: 4.5  # Adjusted for HD
# Add backbone specific HD configurations
BACKBONE2D:
  YOLOv8:
    ver: m
    HD_CONFIG:
      feature_channels: [256, 512, 1024]  # Adjusted for HD
      stride_size: [8, 16, 32]
      memory_efficient: true

BACKBONE3D:
  I3D:
    HD_CONFIG:
      temporal_stride: 2
      spatial_stride: [2, 2, 2, 2]
      memory_efficient: true
  RESNEXT:
    HD_CONFIG:
      temporal_stride: 2
      spatial_stride: [2, 2, 2, 2]
      memory_efficient: true

# Add fusion module HD configurations
fusion_module: CFAM
FUSION:
  CFAM:
    HD_CONFIG:
      channels: [256, 512, 1024]
      attention_reduction: 16
      memory_efficient: true


config_path       : config/ucf_config.yaml
dataset           : ucf
loss              : tal
active_checker    : True
num_classes       : 224
backbone2D        : yolov8
backbone3D        : i3d
fusion_module     : CFAM
mode              : decoupled
interchannels     : [256, 256, 256]
pretrain_path     : /home/manh/checkpoint/ucf24/E30/ema_epoch_7.pth
data_root         : /home/manh/Datasets/UCF101-24/ucf242
img_size          : [1920, 1080]
clip_length       : 16
batch_size        : 4
num_workers       : 8
acc_grad          : 8
lr                : 0.0001
weight_decay      : 0.001
max_step_warmup   : 1000
adjustlr_schedule : [1, 2, 3, 4, 5]
max_epoch         : 10
lr_decay          : 0.5
save_folder       : weights/model_checkpoint
sampling_rate     : 1

# Memory management
memory_efficient: true
mixed_precision: true
gradient_checkpointing: true

# Data augmentation for HD
DATA_AUG:
  enabled: true
  random_crop: [1920, 1080]
  random_flip: true
  random_rotate: [-5, 5]
  color_jitter: 0.1
  adaptive_resize: true

# Validation settings
val_batch_size: 2  # Reduced for HD
val_interval: 1
save_interval: 1

# Hardware optimization
cuda_benchmark: true
cudnn_benchmark: true
num_gpus: 1
distributed: false


idx2name:
  0  : Baseketball
  1  : BaseketballDunk
  2  : Biking
  3  : CliffDiving
  4  : CricketBowling
  5  : Diving
  6  : Fencing
  7  : FloorGymnastics
  8  : GolfSwing
  9  : HorseRiding
  10 : IceDancing
  11 : LongJump
  12 : PoleVault
  13 : RopeClimbing
  14 : SalsaSpin
  15 : SkateBoarding
  16 : Skiing
  17 : Skijet  
  18 : Soccer Juggling
  19 : Surfing
  20 : TennisSwing
  21 : TrampolineJumping
  22 : VolleyballSpiking
  23 : WalkingWithDog
